emoticons = {
"O(<>'<>)O" : "Aang",
'==(:-)=' : 'Abraham Lincoln', 
'=|:)>' : 'Abraham Lincoln', 
'=|:-)' : 'Abraham Lincoln', 
'=|:-)=' : 'Abraham Lincoln', 
'=(_)' : 'Accidental farting', 
':%)' : 'Accountant', 
'?:^[]' : 'Ace Ventura', 
':%)%' : 'Acne', 
'):=' : 'Adolf Hitler', 
'/.#(' : 'Adolf Hitler', 
':-=)' : 'Adolf Hitler', 
'8-[' : 'Afraid', 
'(ap)' : 'Airplane', 
"-|--'" : "Airplane",
':-o' : 'Alarmed', 
'c|B-)' : 'Ali G', 
'(.V.)' : 'Alien', 
'(8>/--<' : 'Alien', 
'OOOOOO' : 'Alien', 
'\^/' : 'Alien', 
'(<>..<>)' : 'Alien', 
'::-)' : 'Alien', 
"'.'" : "Alien",
'>(::O>' : 'Alien', 
'>-)' : 'Alien', 
'<0>..<0>' : 'Alien', 
'((-(-.-)-))' : 'Alien', 
':8)' : 'Alien', 
'>*^,^,^~~~' : 'Alligator', 
'0=)' : 'Angel', 
'^j^' : 'Angel', 
'O:)' : 'Angel', 
'(a)' : 'Angel', 
'O:-)' : 'Angel', 
'O-)' : 'Angel', 
'0-)<' : 'Angel', 
'0;)' : 'Angel', 
'0:)' : 'Angel', 
'0*-)' : 'Angel', 
'():)' : 'Angel', 
'J^' : 'Angel', 
'(angel)' : 'Angel', 
':-t' : 'Angry', 
':-||' : 'Angry', 
'X-(' : 'Angry', 
'X(' : 'Angry', 
':-@' : 'Angry', 
':@' : 'Angry', 
':(' : 'Angry', 
'>-(' : 'Angry', 
'O' : 'Angry', 
'D<' : 'Angry', 
'>:(' : 'Angry', 
'>:-(' : 'Angry', 
'-_-+' : 'Angry', 
':-Z' : 'Angry', 
'(((p(>o<)q)))' : 'Angry', 
':=@' : 'Angry', 
'x=(' : 'Angry', 
'(angry)' : 'Angry', 
'>(' : 'Angry', 
'(_)' : 'Angry', 
'(#_)' : 'Angry', 
'()' : 'Angry', 
'>:-o' : 'Angry', 
'>:-0' : 'Angry', 
'||' : 'Angry', 
'^w^' : 'Anime Smile', 
'-_-;' : 'Anime Sweat Drop', 
"|_|'" : "Anime Sweat Drop",
'^^;' : 'Anime Sweat Drop', 
'@_@' : 'Annoyed', 
'' : 'Annoyed', 
'>_<*' : 'Annoyed', 
':/' : 'Annoyed', 
'>:-(' : 'Annoyed', 
'(_")' : 'Annoyed', 
':42:' : 'Answer to Everything', 
"-o,,o,,o'" : "Ant",
'>:' : 'o Antelope', 
'()' : 'Anticipation', 
'm(_)m' : 'Apology', 
'm(T-T)m' : 'Apology', 
'=D>' : 'Applause', 
'(^^)//' : 'Applause', 
'()' : 'Applause', 
'0-+' : 'April', 
'>A<' : 'Archangel', 
"<')))~" : "Armadillo",
',,\(o3o)/,,' : 'Armpit Hair', 
'>--->>' : 'Arrow', 
'<---<<<' : 'Arrow', 
':arrow:' : 'Arrow', 
'(B-I=' : 'Art Critic', 
'(_)' : 'Ashamed', 
'(_!l)' : 'Ashamed', 
'(_)' : 'Ashamed', 
'(>)' : 'Ashamed', 
'<|-)' : 'Asian', 
'|-I' : 'Asleep', 
'(0)-<-<' : 'Astronaut', 
'~X(' : 'At Wits End', 
'X:-)' : 'Aunt Jemima', 
'(au)' : 'Auto', 
':S' : 'Awkward', 
'o.e' : 'Awkward', 
'Emoticons' : 'that start with B', 
'Emoticon' : 'Meaning', 
':=8)' : 'Baboon', 
'~:0' : 'Baby', 
'~O><' : 'Baby', 
'[{-_-}]' : 'Baby', 
'~:O' : 'Baby', 
'X:-)' : 'Bad hair day', 
'_' : 'Bad hair day', 
'=.=' : 'Bad Idea', 
'C:-|' : 'Bald', 
'(8-)' : 'Bald', 
':-)-S=~' : 'Ballerina', 
'o~' : 'Balloon', 
'((' : 'Banana', 
':' : 'Bandit', 
'(bandit)' : 'Bandit', 
'(headbang)' : 'Banging Head on Wall', 
'(banghead)' : 'Banging Head on Wall', 
"~'v" : "Bangs",
':-%' : 'Banker', 
'~~~' : 'Banksy', 
':-C~' : 'Barfing', 
'8o|' : 'Baring Teeth', 
':-E' : 'Baring Teeth', 
'>--<(:p' : 'Baseball Hat', 
'd:-)' : 'Baseball Player', 
'd:-p' : 'Baseball Player', 
'q:-)' : 'Baseball Player', 
'^v^' : 'Bat', 
'(^+.+^)' : 'Bat', 
'\()/' : 'Bathtub', 
'B-|' : 'Batman', 
'B-)' : 'Batman', 
';;)' : 'Batting Eyelashes', 
'_' : 'Bawling', 
'()' : 'Bawling', 
'(brb)' : 'Be Right Back', 
"('')-.-('')" : "Bear",
"\'''\(*.*)/'''/" : "Bear",
'o' : 'o', 
'O_______' : 'O', 
'(""\(O_O)/"")' : 'Bear', 
'(()' : 'Bear', 
'(())' : 'Bear', 
'(())' : 'Bear', 
'()' : 'Bear', 
"(''')-.-(''')" : "Bear",
'' : 'Bear', 
'(())' : 'Bear', 
'' : 'Bear cub', 
'()' : 'Bear cub', 
':)#' : 'Beard', 
'(:-{~' : 'Beard', 
':-)}' : 'Beard', 
'b-(' : 'Beat Up', 
'%+|' : 'Beaten Up', 
'(#_#)' : 'Beaten Up', 
'(*@_#)' : 'Beaten Up', 
'(O_.)' : 'Beaten Up', 
'(=_)' : 'Beaten Up', 
'0___' : 'Bed', 
'X:-|' : 'Bed Head', 
'~(,)~' : 'Bee', 
':bz' : 'Bee', 
'(b)' : 'Beer Mug', 
'___' : '', 
'|__|/' : 'Beer Mug', 
'[%]D' : 'Beer Mug', 
'(beer)' : 'Beer Mug', 
'(bricklayers)' : 'Beer Mug', 
'(_)3' : 'Beer Mug', 
'm(-_-)m' : 'Begging', 
'::::[||]::::' : 'Belt', 
'_' : 'Benjamin Franklin', 
'OTL' : 'Bent Over', 
'' : 'Best Buds', 
'&:-o-8-<' : 'Betty Boop', 
'#:o+=' : 'Betty Boop', 
'o_0' : 'Bewildered', 
'(".")' : 'Bewildered', 
'|_______|' : 'Bible', 
':D' : 'Big Grin', 
':-D' : 'Big Grin', 
':grin:' : 'Big Grin', 
':=D' : 'Big Grin', 
'(laugh)' : 'Big Grin', 
'()' : 'Big Grin', 
'>:D<' : 'Big Hug', 
'8|___)' : 'Big Laugh', 
':-(|)' : 'Big Lips', 
'(|X0||)' : 'Big Mac', 
'o=>' : 'Billy', 
'(*v*)' : 'Bird', 
'<;' : 'O', 
'(' : 'Bird', 
'=W' : 'Bird', 
'~:<>' : 'Bird', 
'/"' : 'Bird', 
'V' : 'Bird', 
'(8>)<' : 'Bird', 
'~O~' : 'Bird', 
'll' : 'Bird', 
'0>' : 'Bird', 
'{v}' : 'Bird', 
'(`)' : 'Bird', 
'()' : 'Bird', 
'' : 'Bird', 
'()' : 'Bird', 
'(^)' : 'Birthday Cake', 
'(cake)' : 'Birthday Cake', 
'*<:)' : 'Birthday Hat', 
'<>:-)' : 'Bishop', 
':*x' : 'Biting', 
':-s' : 'Bizzare Comment', 
'(:-D' : 'Blabber Mouth', 
'!-(' : 'Black Eye', 
'?-(' : 'Black Eye', 
'(bah)' : 'Black Sheep', 
"'8^P" : "Blah",
'|-(' : 'Blind', 
'#-)' : 'Blinking', 
'^^' : 'Blissful', 
':c)' : 'Blissful', 
'<^^*>' : 'Blissful', 
'(@)/(@)' : 'Bloodshot Eyes', 
'(O)' : 'Blowfish', 
'(--)*' : 'Blowing a Kiss', 
'*8=(:' : 'Blubbering', 
':-">' : 'Blushing', 
":,')" : "Blushing",
'=">' : 'Blushing', 
':-*>' : 'Blushing', 
'=^}' : 'Blushing', 
':")' : 'Blushing', 
'=^_^=' : 'Blushing', 
'=<_<=' : 'Blushing', 
':*-)' : 'Blushing', 
':">' : 'Blushing', 
':8}' : 'Blushing', 
'(blush)' : 'Blushing', 
':=$' : 'Blushing', 
'>//<' : 'Blushing', 
'c-----7' : 'Boat', 
'@=' : 'Bomb', 
'*' : 'Bomb', 
'(_)' : 'Boogie down', 
'()' : 'Booing', 
':-o' : 'Bored', 
':/' : 'Bored', 
'(-_-)' : 'Bored', 
'\-o' : 'Bored', 
':-o' : 'zz Bored', 
':z' : 'Bored', 
'(_)' : 'Borg', 
'(/-_)/D>' : 'Bow and Arrow', 
':-)8' : 'Bow Tie', 
':-)x' : 'Bow Tie', 
'orz' : 'Bowing', 
'(bow)' : 'Bowing', 
'(||)' : 'Bowl', 
'===O____iii' : 'Bowling', 
'_____O___III' : 'Bowling', 
'____o/|||' : 'Bowling', 
'o(^_-)O' : 'Boxer', 
'O??' : 'Boxer', 
'(z)' : 'Boy', 
'(:-)' : 'Boy', 
':-)^<' : 'Boy', 
':-#' : 'Braces', 
':-{#}' : 'Braces', 
'=#' : 'Braces', 
'%-6' : 'Brain Dead', 
'[<O>]' : 'Brazilian Flag', 
'' : 'Bread', 
'>:/' : 'Bring it On', 
'%-(' : 'Broken Glasses', 
'</3' : 'Broken Heart', 
'(U)' : 'Broken Heart', 
'=((' : 'Broken Heart', 
'<~3' : 'Broken Heart', 
'<\3' : 'Broken Heart', 
'(brokenheart)' : 'Broken Heart', 
':-(=)' : 'Buckteeth', 
':B' : 'Bucktooth', 
'(*^o^)(^o^*)' : 'Buddies', 
'}|{' : 'Bug', 
'=:)' : 'Bug', 
'()_()' : 'Bug', 
'(bug)' : 'Bug', 
'E=B' : 'Bugs Bunny', 
"pq`#'" : "Bull",
'):|' : 'Bull', 
'3:(:)' : 'Bull', 
'[O==O\=<(' : 'Bulldozer', 
'o^o-o{' : 'Bulldozer', 
'=;-(' : 'Bully', 
'(_)' : 'Bummed out', 
'(")(")' : 'Bunny', 
'(")(")' : 'Bunny', 
"('')_('')" : "Bunny",
'-()()-' : 'Bunny', 
'' : 'U U  Bunny', 
'(=^_^=)' : 'Bunny', 
"(='.')" : "Bunny",
'(O:3' : 'Bunny', 
'(")_(")' : 'Bunny', 
'o(_-\_' : 'Bunny', 
'()' : 'Bunny', 
'U.U' : 'Bunny', 
'(\_/)' : 'Bunny Ears', 
'#-(' : 'Bureaucrat', 
'(bus)' : 'Bus', 
'[===]' : 'Bus', 
':-)<////>' : 'Businessman', 
'()' : 'But At What Cost', 
'(_|_)' : 'Butt', 
'(_!_)' : 'Butt', 
'}i{' : 'Butterfly', 
'})i({' : 'Butterfly', 
'})U({' : 'Butterfly', 
'' : 'Butterfly', 
'Emoticons' : 'that start with C', 
'Emoticon' : 'Meaning', 
'`-----------`' : 'Cake', 
'(call)' : 'Call', 
':-c' : 'Call Me', 
"~M'" : "Camel",
'(p)' : 'Camera', 
'|C|' : 'Can of Coke', 
'|P|' : 'Can of Pepsi', 
'o=' : 'Candle', 
'-=' : 'Candle', 
'~=' : 'Candle', 
'~===|' : 'Candle', 
'>(///)<' : 'Candy', 
'P=\\' : 'Cap', 
'__' : '', 
'((-_(-_-)_-))' : 'Care Crowd', 
'(^o)(^0^)(o^)' : 'Caroling', 
'(cash)' : 'Cash', 
'(mo)' : 'Cash', 
'($)' : 'Cash', 
'|*-*|' : 'Cassette Tape', 
">'o'<" : "Cat",
'=^.^=' : 'Cat', 
'>;3' : 'Cat', 
',,,^..^,,,~' : 'Cat', 
'~' : 'Cat', 
">'.'<" : "Cat",
'(^-_-^)' : 'Cat', 
'<^oo^>' : 'Cat', 
'=^_^=' : 'Cat', 
'(==)' : 'Cat', 
'(=^^=)' : 'Cat', 
'>^..^<' : 'Cat Face', 
'(@)' : 'Cat Face', 
'<^..^>' : 'Cat Face', 
'^-.-^' : 'Zzzzz Cat Nap', 
'(:@@@@@D' : 'Caterpillar', 
'<0_/\_/\_' : 'Caterpillar', 
'~o(:-)' : 'Cave Diver', 
'(O)' : 'Celebrate', 
'(<._.>)' : 'Charlie Brown', 
'|-{' : 'Charlie Brown', 
'C|:-=' : 'Charlie Chaplin', 
'()' : 'Chasing A Butterfly', 
':-@' : 'Chatterbox', 
'\o/' : 'Cheer', 
'' : 'Cheerful', 
'' : 'Cheerful', 
'()' : 'Cheerful', 
'*\O/*' : 'Cheerleader', 
'C=:-)' : 'Chef', 
'(:=3' : 'Chef', 
'~:>' : 'Chicken', 
'<)' : 'Chicken', 
'(*>' : 'Chicken', 
'8^' : 'Chicken', 
'-{:-]' : 'Chinese Hat', 
':putnam:' : 'Chris Putnam', 
'*<<<<=' : 'Christmas Tree', 
'' : 'X', 
'|_|' : 'Christmas Tree', 
'|' : 'Christmas Tree', 
'^)_(^' : 'Chubby', 
'<{^-^}>' : 'Chubby Face', 
'(ci)' : 'Cigarette', 
'=====~' : 'Cigarette', 
':-.)' : 'Cindy Crawford', 
'(:)' : 'Clam', 
'(clap)' : 'Clapping', 
'()//' : 'Clapping', 
'(o)' : 'Clock', 
'<]:o){' : 'Clown', 
':O)' : 'Clown', 
'*:o)' : 'Clown', 
'<|:^0|<' : 'Clown', 
'*<:o)' : 'Clown', 
'*<:^)' : 'Clown', 
'*<:oP' : 'Clown', 
'*<:oB' : 'Clown', 
'(c:>*' : 'Clown', 
'*<8-)X' : 'Clown', 
'><*:oDX' : 'Clown', 
'' : 'Clown', 
'=:-)' : 'Cobbler', 
'(C)' : 'Coffee Cup', 
'C[_]' : 'Coffee Cup', 
'~0)|' : 'Coffee Cup', 
'(coffee)' : 'Coffee Cup', 
':-{}' : 'Cold', 
'' : 'Cold', 
'?_?' : 'Cold Stare', 
'$:-)' : 'Comb Stuck in the Hair', 
'(;)(-_-)' : 'Comforting', 
'(co)' : 'Computer', 
'_____' : '', 
'|O-O|' : '', 
'|:::|' : '', 
'-----' : 'Computer', 
'@/:^)' : 'Conan', 
':-r' : 'Concentrating', 
':-8(' : 'Condescending', 
':^)' : 'Confounded', 
'O.o' : 'Confused', 
':-Q' : 'Confused', 
':-/' : 'Confused', 
':-S' : 'Confused', 
':s' : 'Confused', 
':-$' : 'Confused', 
'(@_@)' : 'Confused', 
'-' : 'Confused', 
'=?' : 'Confused', 
",':(" : "Confused",
'O.o?' : 'Confused', 
':-??' : 'Confused', 
'0' : '0', 
'__' : 'Confused', 
'(p_q)' : 'Confused', 
'\(_o)/' : 'Confused', 
'?:|' : 'Confused', 
'-.-?' : 'Confused', 
'(-?)' : 'Confused', 
'()' : 'Confused', 
'(-_-)' : 'Confused', 
':?' : 'Confused', 
':-?' : 'Confused', 
':???:' : 'Confused', 
'o_O' : 'Confused', 
'(??)' : 'Confused', 
'8-/' : 'Confused', 
'8/' : 'Confused', 
'' : 'Content', 
'B-)' : 'Cool', 
'0' : '0', 
'-' : 'Cool', 
'qB-)' : 'Cool', 
'-D' : 'Cool', 
'8=)' : 'Cool', 
'B=)' : 'Cool', 
'(cool)' : 'Cool', 
':B)' : 'Cool', 
'B)' : 'Cool', 
'-<0oo' : 'Corn', 
'3:-O' : 'Cow', 
'3:O' : 'Cow', 
'3:08' : 'Cow', 
'<):-)' : 'Cowboy', 
'}:-)' : 'Cowboy', 
'<):)' : 'Cowboy', 
'C):)' : 'Cowboy', 
'(-:(3' : 'Cowboy', 
'C):-)' : 'Cowboy', 
'{:-)' : 'Cowgirl', 
')O{)|><' : 'Cowgirl', 
'V.v.V' : 'Crab', 
'V.^.' : 'V', 
'(\/)!_!(\/)' : 'Crab', 
'' : 'Crab', 
'()_RED_(>' : 'Crayon', 
'())Crayola))>' : 'Crayon', 
'(_)' : 'Crazed', 
'%-)' : 'Crazy', 
'()' : 'Crazy', 
'>,=,-' : 'Crocodile', 
':_(' : 'Crying', 
':*(' : 'Crying', 
'T_T' : 'Crying', 
':((' : 'Crying', 
":'(" : "Crying",
';_;' : 'Crying', 
'QQ' : 'Crying', 
':..[' : 'Crying', 
'T^T' : 'Crying', 
"='(" : "Crying",
'8:::(' : 'Crying', 
'TT^TT' : 'Crying', 
'TT_TT' : 'Crying', 
'i_i' : 'Crying', 
":'-C" : "Crying",
';-;' : 'Crying', 
':"-(' : 'Crying', 
':~-(' : 'Crying', 
'TT.TT' : 'Crying', 
'(!_!)' : 'Crying', 
'&.(..' : 'Crying', 
'(ToT)' : 'Crying', 
'(;_;)' : 'Crying', 
":'-(" : "Crying",
';(' : 'Crying', 
'Y.Y' : 'Crying', 
'T.T' : 'Crying', 
':cry:' : 'Crying', 
';=(' : 'Crying', 
'(cry)' : 'Crying', 
'(-__-)' : 'Crying', 
'|_|' : 'Cup', 
'C(_)' : 'Cup', 
'|_P' : 'Cup', 
'C(_)' : 'Cup of Coffee', 
'|_P' : 'Cup of Coffee', 
'~o)' : 'Cup of Coffee', 
'[_]P' : 'Cup of Coffee', 
'@:-)' : 'Curly Hair', 
'8:-)' : 'Curly Hair', 
':-@!' : 'Cursing', 
'X3' : 'Cute', 
'n_n' : 'Cute', 
'||' : 'Cutting a rug', 
'@-|' : 'Cyborg', 
'()' : 'Cyborg', 
'o-)' : 'Cyclops', 
'O-(' : 'Cyclops', 
'.)' : 'Cyclops', 
'Q-)' : 'Cyclops', 
'*-(' : 'Cyclops', 
'>P-(' : 'Cyclops', 
':/7)' : 'Cyrano de Bergerac', 
'Emoticons' : 'that start with D', 
'Emoticon' : 'Meaning', 
':)-S=' : 'Dancer', 
'\:D/' : 'Dancing', 
'<(..<)' : 'Dancing', 
'(>..)>' : 'Dancing', 
'~(o.o)~' : 'Dancing', 
'(^_^)(^_^)' : 'Dancing', 
'v(*.*)^' : 'Dancing', 
'(~^.^)~' : 'Dancing', 
'(dance)' : 'Dancing', 
'\o/' : 'Dancing', 
'(.)' : 'Dancing', 
'^^)' : 'Dancing', 
'(o)' : 'Dancing', 
'(o)' : 'Dancing', 
'C8<]' : 'Darth Vader', 
'()' : 'Darth Vader', 
'Q:|' : 'Davey Crockett', 
'8->' : 'Daydreaming', 
'*-*' : 'Dazed', 
'**' : 'Dazed', 
'[*_*]' : 'Dazzled', 
'x_x' : 'Dead', 
'-' : 'Dead', 
'x.x' : 'Dead', 
'XP' : 'Dead', 
'8-#' : 'Dead', 
'X' : 'X', 
'U' : 'Dead', 
'(X_X)' : 'Dead', 
'(+_+)' : 'Dead', 
"'-=,o" : "Dead",
'(#_)' : 'Dead', 
'>T_T' : 'Dead', 
'(u_u)' : 'Dead', 
'(==)' : 'Dead cat', 
'()' : 'Deceased', 
'~(O)|' : 'Deep Sea Diver', 
'3:*)' : 'Deer', 
'(T_T)->' : 'Defeated', 
'(_)' : 'Defeated', 
'^(#)_' : 'Demon', 
'(<_>)' : 'Depressed', 
'._.' : 'Depressed', 
'-----' : 'Depressed', 
'(._.)' : 'Depressed', 
'c_*' : 'Depressed', 
'_' : 'Depressed', 
'(;)' : 'Depressed', 
':-[' : 'Despondent', 
'i-)' : 'Detective', 
'()' : 'Devastated', 
'>:)' : 'Devil', 
'(6)' : 'Devil', 
']:->' : 'Devil', 
'}:-)' : 'Devil', 
'()}:o)' : 'Devil', 
'}=^{|~' : 'Devil', 
'3:)' : 'Devil', 
'>:-)~' : 'Devil', 
'>;->' : 'Devil', 
'3:-)' : 'Devil', 
':evil:' : 'Devil', 
'(devil)' : 'Devil', 
':[' : 'Devil', 
':-[' : 'Devil', 
'>:->' : 'Diabolical', 
'[](*' : 'Dialing', 
'{>O' : 'Diamond Ring', 
":-')" : "Dimple",
'/\"' : 'Dinosaur', 
'_..._' : '', 
'=|:-)X' : 'Diplomat', 
':-|' : 'Disappointed', 
':|' : 'Disappointed', 
':(&' : 'Disappointed', 
'=\"' : 'Disappointed', 
'Disappointe' : 'd', 
'_' : 'Disapproval', 
'/' : 'Discarding', 
'' : 'Discontent', 
'DX' : 'Disgusted', 
':' : 'Disgusted', 
'-__-' : 'Disinterested', 
'(*m)' : 'Dissatisfied', 
'/:(' : 'Distraught', 
'_' : 'Distressed', 
'%-}' : 'Dizzy', 
'd[-_-]b' : 'DJ', 
'[:-}' : 'DJ', 
'd^_^b' : 'DJ', 
':-$' : 'Do Not Tell Anyone', 
':-)-o' : 'Doctor', 
'O:v)>--o' : 'Doctor', 
':O?' : 'Dog', 
':O/' : 'Dog', 
':O$' : 'Dog', 
':O)' : 'Dog', 
'<[.,=.,]-' : 'Dog', 
'<[~.~]>' : 'Dog', 
':o3' : 'Dog', 
'<*^)' : '', 
'<*^)' : '', 
':3-<' : 'Dog', 
'/(^.^)\"' : 'Dog', 
'(UxU)' : 'Dog', 
'UU' : 'Dog', 
'' : 'Dog', 
'U)~' : 'Dog', 
'' : 'Dog', 
'' : 'Dog', 
'8==3' : 'Dog Bone', 
'&===3' : 'Dog bone', 
'(&)' : 'Dog Face', 
'VV' : 'Doggy', 
'(>.<)' : 'Doh', 
'[$(1)$]' : 'Dollar', 
'===:-D' : 'Don King', 
'(8)<=' : 'Doraemon', 
':D))' : 'Double Chin', 
':' : 'T Doubtful', 
'}:-(=' : 'Dracula', 
'(>:^F)' : 'Dracula', 
'^.=.^' : 'Dragon', 
'<*,^^,--' : 'Dragon', 
'I-)' : 'Dreaming', 
'*DRINK*' : 'Drink', 
'\%/' : 'Drink', 
'=P~' : 'Drooling', 
':-P' : 'Drooling', 
':P' : 'Drooling', 
'*DROOLING*' : 'Drooling', 
':)_' : 'Drooling', 
':-B' : 'Drooling', 
'(**)' : 'Drooling', 
'~~~~\o/~~~~' : 'Drowning', 
':*)' : 'Drunk', 
':*)?' : 'Drunk', 
'%-<I>' : 'Drunk', 
':#)' : 'Drunk', 
'(drunk)' : 'Drunk', 
'o_O' : 'Drunk', 
'_|V|_' : 'Duck', 
'8()' : 'Duck', 
'\_O<' : 'Duck', 
':-F' : 'Dufus', 
'|-(' : 'Dull', 
'|(' : 'Dull', 
'|=(' : 'Dull', 
'p^b' : 'Dumb', 
'8)' : 'Dumb Person', 
'Oo!' : 'Dumbfounded', 
'<:-|' : 'Dunce', 
'<:-)' : 'Dunce', 
'()))TNT)))-x' : 'Dynamite', 
'Emoticons' : 'that start with E', 
'Emoticon' : 'Meaning', 
'' : 'Eager', 
'p^_^q' : 'Earphones', 
'::--((' : 'Earthquake', 
':g' : 'Eating', 
':K' : 'Eating', 
'()' : 'Edward Scissorhands', 
'()' : 'Edward Scissorhands', 
'(:-|' : 'Egghead', 
'~~~\8-O' : 'Electrocuted', 
'\/\/\/\,8-O' : 'Electrocuted', 
':~' : 'Elephant', 
'~:3' : 'Elephant', 
'\_/' : 'Elephant', 
"~MC'~" : "Elephant",
'}.' : 'Elephant', 
'*<:-)-:--:' : 'Elf', 
'' : 'Elton John', 
'@=)' : 'Elvis', 
'2:)' : 'Elvis', 
'?:-p' : 'Elvis', 
':-[]' : 'Elvis', 
'5:-)' : 'Elvis Presley', 
'&:-)' : 'Elvis Presley', 
':-$' : 'Embarrassed', 
':$' : 'Embarrassed', 
':-[' : 'Embarrassed', 
'^^"' : 'Embarrassed', 
'(#^.^#)' : 'Embarrassed', 
':oops:' : 'Embarrassed', 
'(*/*)' : 'Embarrassed', 
'Embarrasse' : 'd', 
'(##)' : 'Embarrassed', 
'//_^' : 'Emo', 
'T-T' : 'Emo', 
'(//.^)' : 'Emo', 
'(//_^)' : 'Emo', 
'(//_-)' : 'Emo', 
'c//_+.' : 'Emo', 
"c//_^'" : "Emo",
'c/_-*' : 'Emo', 
'(-_\\\)' : 'Emo', 
'//_T)o.' : 'Emo', 
'd(//^)b' : 'Emo', 
'\/O\/O\/' : 'Emo', 
'(emo)' : 'Emo', 
',_' : 'Emo', 
'(///.-)' : 'Emo', 
'' : 'Enamored', 
'(*m*)' : 'Enraged', 
'(v)' : 'Envious', 
'(envy)' : 'Envious', 
'(@){' : 'Euphonium', 
'((((((^_^;)' : 'Evading', 
'>:3' : 'Evil Cuteness', 
'(.\|/.)' : 'Evil Face', 
'):D}' : 'Evil Face', 
':{)' : 'Evil Face', 
'>:~>' : 'Evil Face', 
'>:{)>' : 'Evil Face', 
']}:-)>' : 'Evil Face', 
'>-)' : 'Evil Grin', 
'>:)' : 'Evil Grin', 
']:)' : 'Evil Grin', 
':twisted:' : 'Evil Grin', 
'(grin)' : 'Evil Grin', 
'>:D' : 'Evil Laugh', 
'()' : 'Evil Laugh', 
'>=)' : 'Evil Smile', 
'/^^\!' : 'Exasperated', 
':-O' : 'Excited', 
'(*-*)' : 'Excited', 
':o' : 'Excited', 
'(^O^)' : 'Excited', 
'()' : 'Excited', 
'#-)' : 'Exhausted', 
'||' : 'Exhausted', 
'(;?`)' : 'Exhausted', 
'STO' : 'Exhausted', 
'(((ToT)~~' : 'Exorcism', 
'_(*)' : 'Exorcism', 
'<>' : 'Eye', 
'P-)' : 'Eye Patch', 
'b-)' : 'Eye Patch', 
'' : 'Eye Roll With Hands Up', 
'}=D' : 'Eyebrows', 
'-@--@-' : 'Eyeglasses', 
'Emoticons' : 'that start with F', 
'Emoticon' : 'Meaning', 
':&' : 'Fail', 
'(6.6)' : 'Fainting', 
'(_)' : 'Fake Smile', 
'?:-)' : 'Fancy Hair', 
'o,..,o' : 'Fangs', 
'^,..,^' : 'Fangs', 
'(0)' : 'Fed Up', 
'=^O.O^=' : 'Felix the Cat', 
'' : 'O', 
'+' : 'Female', 
'' : 'O', 
'' : '', 
'^' : 'Female', 
'O<-<=' : 'Female', 
';~[' : 'Fighter', 
'' : '', 
'(~)' : 'Filmstrip', 
'(yn)' : 'Fingers Crossed', 
'X=' : 'Fingers Crossed', 
'()))))-x' : 'Firecracker', 
'}-(((*>' : 'Fish', 
'<")))><' : 'Fish', 
'><(((">' : 'Fish', 
'<.{{{><' : 'Fish', 
'{}{' : 'Fish', 
'<><' : 'Fish', 
'<((((><' : 'Fish', 
"<('O')>" : "Fish",
'<*)))<' : 'Fish', 
'|>///^<' : 'Fish', 
'>)##)' : 'Fish', 
')' : 'Fish', 
'()#))<<' : 'Fish', 
"<')+++<" : "Fish Bone",
'(~)' : 'Fish Bowl', 
'p#d' : 'Fist Bump', 
'i-=<***' : 'Flamethrower', 
"!.'v" : "Flat Top",
'OZ~<' : 'Flexing', 
'(_)' : 'Flexing', 
'()' : 'Flexing', 
'()' : 'Flipping Table', 
'()' : 'Flipping Table', 
'()' : 'Flipping Table', 
';D' : 'Flirting', 
';-)' : 'Flirty', 
'(ff)' : 'Flirty Female', 
';3' : 'Flirty Grin', 
'(fm)' : 'Flirty Male', 
'@>---' : 'Flower', 
'@>--;--' : 'Flower', 
'<-#' : 'Flower', 
"@-'-" : "Flower",
'(f)' : 'Flower', 
'(flower)' : 'Flower', 
'###' : 'Flower', 
'0==I==,==I===' : 'Flute', 
"D';" : "FML",
'O-&-<' : 'Folding Arms', 
':-!' : 'Foot in Mouth', 
'()' : 'Football', 
'G:-)' : 'Football Helmet', 
'=:-H' : 'Football Player', 
'C:#' : 'Football Player', 
'---E' : 'Fork', 
'o^o-o|_' : 'Forklift', 
'|:-<' : 'Forlorn', 
'%%-' : 'Four Leaf Clover', 
'88-' : 'Four Leaf Clover', 
'Vm~' : 'Fox', 
':^{=' : 'Frank Zappa', 
'E:/' : 'Frankenstein', 
'[:-|I' : 'Frankenstein', 
'[8-]' : 'Frankenstein', 
'()' : 'Frantic', 
'()' : 'Frantic', 
'()' : 'Freak Out', 
'()' : 'Freak Out', 
":'|" : "Freezing",
':pd:' : 'French Kiss', 
':bq:' : 'French Kiss', 
':bd:' : 'French Kiss', 
'(`*)' : 'Friendly', 
'O' : 'O', 
'8-|' : 'Frightened', 
'()' : 'Frightened', 
'8)~~*' : 'Frog', 
'8)' : 'Frog', 
':(?)' : 'Frog', 
':()' : 'Frog', 
'[II]D' : 'Frosty Mug', 
'' : 'Frosty the Snowman', 
'' : 'Frosty the Snowman', 
':-(' : 'Frown', 
':(' : 'Frown', 
':o{' : 'Frown', 
':-(' : 'Frowning', 
'=P' : 'Frustrated', 
'X[' : 'Frustrated', 
':-P' : 'Frustrated', 
'><' : 'Frustrated', 
'B/' : 'Frustrated', 
'>.<*' : 'Frustrated', 
'-_-*' : 'Frustrated', 
':-L' : 'Frustrated', 
'()' : 'Fu Manchu Man', 
'(fubar)' : 'FUBAR', 
'|-[#]' : 'Fuming', 
'B-}' : 'Funny', 
'(_)' : 'Furious', 
'*:*' : 'Fuzzy', 
'Emoticons' : 'that start with G', 
'Emoticon' : 'Meaning', 
':-(*)' : 'Gag Me', 
'qB]' : 'Gangster', 
'@}:-)' : 'Gardener', 
'=:o' : 'Gasp', 
'' : 'Geek', 
'3>(' : 'Geezer', 
'(D:-]' : 'General', 
'@:i' : 'Genie', 
'{@:)}' : 'Genie', 
'4:-)' : 'George Washington', 
'd=P' : 'Ghetto', 
'(>")>' : 'Ghost', 
'<(")>' : 'Ghost', 
'(",)' : 'Ghost', 
'(boo)' : 'Ghost', 
'()' : 'Ghost', 
'((()))' : 'Ghost', 
'8[+]' : 'Gift', 
'()' : 'Gift', 
'(g)' : 'Gift with a Bow', 
';))' : 'Giggle', 
'*GIGGLING*' : 'Giggling', 
'(giggle)' : 'Giggling', 
'(chuckle)' : 'Giggling', 
'()' : 'Giggling', 
'>:o===Q<' : 'Giraffe', 
'(x)' : 'Girl', 
'8:^)' : 'Girl', 
'(-_-)#' : 'Girl', 
'~0(**)0~' : 'Girl', 
'(;`)' : 'Giving Up', 
'' : 'Glad', 
'>:[' : 'Glaring', 
'\~/' : 'Glass', 
'\_/' : 'Glass', 
'??' : 'Glasses', 
'-o-o-' : 'Glasses', 
'8-)' : 'Glasses', 
'()-()' : 'Glasses', 
'-@--@-' : 'Glasses', 
'\o-o/' : 'Glasses', 
'(-_q)' : 'Glasses', 
'8)' : 'Glasses', 
'B-)' : 'Glasses', 
'B)' : 'Glasses', 
'(^0_0^)' : 'Glasses', 
'' : 'Gleeful', 
'(nah)' : 'Goat', 
'(nnh)' : 'Goat', 
':-{>' : 'Goatee', 
';' : 'Goatee', 
'):()-' : 'Goatee', 
'o/' : 'Golf', 
'()' : 'Golf Clap', 
'' : 'Good Morning', 
'(`)' : 'Good Night', 
'(ToT)/~~~' : 'Goodbye', 
':8]' : 'Gorilla', 
'%:O' : 'Gorilla', 
'8:]' : 'Gorilla', 
'|<:-)' : 'Graduate', 
'L:-)' : 'Graduate', 
'Q:-)' : 'Graduate', 
'oO:)&' : 'Grandma', 
'' : 'Grandma', 
'(~};)' : 'Grateful Dead', 
'$_$' : 'Greedy', 
'($v$)' : 'Greedy', 
'$__$' : 'Greedy', 
".'!" : "Grim",
':->' : 'Grin', 
':D' : 'Grin', 
'-D' : 'Grin', 
':oP' : 'Grin', 
'' : 'Grinning', 
'(-_' : 'Groggy', 
'v(*.*)^' : 'Grooving', 
'(^o^)' : 'Grooving', 
':-!' : 'Gross', 
"l:['" : "Groucho Marx",
'[>#<]' : 'Grouchy', 
'(.(.).)' : 'Group', 
'>:(' : 'Grumpy', 
'^i^' : 'Guardian Angel', 
'>I<' : 'Guardian Angel', 
'^_^;' : 'Guilty', 
'(____)' : 'Guitar', 
'(_|||_)' : 'Guitar', 
'=' : 'Gun', 
'' : 'Gun', 
'' : 'Gun', 
'' : 'Gun', 
'S:~)' : 'Guy', 
'$8()' : 'Guy with a Toupee', 
'Emoticons' : 'that start with H', 
'Emoticon' : 'Meaning', 
'*8D' : 'Hair', 
'((:D' : 'Hair', 
'~~8-O' : 'Hair', 
'@:-)' : 'Hair', 
'#:-)' : 'Hair', 
'~#:-(' : 'Hair', 
'?:-)' : 'Hair', 
'%-.-%' : 'Hair', 
"@.'v" : "Hair",
'{:-{)}' : 'Hairy', 
'L-:' : 'Half Smile', 
'(||]' : 'Hamburger', 
'(%)' : 'Handcuffs', 
'(:>-<' : 'Hands Up', 
':-|><' : 'Hands Up', 
'(handshake)' : 'Handshake', 
'&:-]' : 'Handsome', 
'=)' : 'Happy', 
'U' : 'Happy', 
':-)' : 'Happy', 
':)' : 'Happy', 
'^.^' : 'Happy', 
'^^' : 'Happy', 
'(:' : 'Happy', 
'|___|' : 'Happy', 
'^-^' : 'Happy', 
'8D' : 'Happy', 
'(^_^)' : 'Happy', 
'8^)' : 'Happy', 
':-}' : 'Happy', 
'!_!' : 'Happy', 
':)))' : 'Happy', 
'(happy)' : 'Happy', 
'()' : 'Happy', 
'' : 'Happy', 
'' : 'Happy', 
'o' : 'Happy', 
'B^)' : 'Happy', 
'8-D' : 'Happy', 
'BD' : 'Happy', 
'B^D' : 'Happy', 
'8^D' : 'Happy', 
'' : 'Happy', 
'*<|:o)' : 'Happy Birthday', 
'()' : 'Happy crying', 
':")' : 'Happy Tears', 
'|||)' : 'Harp', 
'<~8)' : 'Harry Potter', 
'>O<' : 'Harry Potter Snitch', 
'#' : 'Hashtag', 
'q=)' : 'Hat', 
'xd:)' : 'Hat', 
'*<:)' : 'Hat', 
'+(:-)' : 'Hat', 
"*<.'v" : "Hat",
"d.'v" : "Hat",
'\,,/(>.<)\,,/' : 'Head Banging', 
'(({..}))' : 'Headache', 
'(|:-)' : 'Headband', 
'>:^(' : 'Headhunter', 
'oo' : 'Headlights', 
'0(o.o)0' : 'Headphones', 
'd(-_-)b' : 'Headphones', 
'[:-)' : 'Headphones', 
"q[-'.'-]p" : "Headphones",
'dL-_-b' : 'Headset', 
'<3' : 'Heart', 
'<u3' : 'Heart', 
'S2' : 'Heart', 
'' : 'Heart', 
'-(`.)->' : 'Heart', 
'(h)' : 'Heart', 
'(l)' : 'Heart', 
'(heart)' : 'Heart', 
'./\..|..|....' : 'Heart Monitor', 
'()' : 'ol Heartbroken', 
'\,,/' : 'Heavy Metal', 
'(heidy)' : 'Heidy', 
'o_o' : 'Hello', 
'(o)' : 'Help', 
'()!!' : 'Help', 
'?:)#' : 'Hema Employee', 
'' : 'Herp Derp', 
'(_;)_)' : 'Hiding', 
'(_|' : 'Hiding', 
'|)' : 'Hiding', 
'|_)' : 'Hiding', 
'~~' : 'High Brow', 
'(h5)' : 'High Five', 
'o/\o' : 'High Five', 
'^_^/' : 'High Five', 
'(*)(*)' : 'High Five', 
'^y^-/|\--Y^' : 'Highway', 
'o->' : 'Hiro', 
':-/' : 'Hmmm', 
'(#]' : 'Hockey Player', 
'L.' : 'Hockey Stick', 
'L.' : 'Hockey Stick and Puck', 
'8-)' : 'Hollywood', 
'(_8^(|)' : 'Homer', 
'(8-(1)' : 'Homer', 
'(_8^(1)' : 'Homer Simpson', 
'~(_8^(|)' : 'Homer Simpson', 
'o--}' : 'Hope', 
'o(^^o)(o^^)o' : 'Hopeful', 
'}:)' : 'Horny', 
'O_' : '0', 
'[_]' : 'Horror', 
']:-:)' : 'Horse', 
'(h)' : 'Hot', 
'(;)' : 'How Should I Know', 
'(:)\/<' : 'Hug', 
':)X' : 'Hug', 
"(>'')><(''<)" : "Hug",
'(((H)))' : 'Hug', 
'{}' : 'Hug', 
'({})' : 'Hug', 
'(bear)' : 'Hug', 
'(hug)' : 'Hug', 
'()' : 'Hug', 
'{*}' : 'Hug and Kiss', 
'd=()=b' : 'Hug me', 
'<(^.^<)' : 'Huge', 
'(>^_^)><(^o^<)' : 'Hugging', 
'<(*.*<)' : 'Huggle', 
':D<' : 'Hugs', 
'((()))' : 'Hugs', 
'{{{***}}}' : 'Hugs and Kisses', 
'[.]' : 'Huh', 
'~!~' : 'Humbled', 
'%*@:-(' : 'Hung Over', 
':0' : 'Hungry', 
':-[]' : 'Hungry', 
':!!' : 'Hurry Up', 
'XD' : 'Hyper', 
'U' : 'Hypnotist', 
'@-)' : 'Hypnotized', 
'Emoticons' : 'that start with I', 
'Emoticon' : 'Meaning', 
':^)' : 'I Do Not Know', 
'X_X' : 'I Do Not Want to See', 
'_\m/' : 'I Love You', 
'~oO>' : 'Ice Cream Cone', 
'<OO' : 'Ice Cream Cone', 
'<Oo*' : 'Ice Cream Cone', 
'<><' : 'Ichthus', 
'*-:)' : 'Idea', 
':idea:' : 'Idea', 
'*help' : 'IM', 
'*red+u' : 'IM', 
':!:' : 'Important', 
'O-S-<' : 'In a hurry', 
'(@)' : 'In a Nut Shell', 
'(*_*)' : 'In Love', 
'<3+<3' : 'In Love', 
'(_)' : 'In Love', 
':]' : 'In Love', 
'(inlove)' : 'In Love', 
'(love)' : 'In Love', 
':-]' : 'In Love', 
'._.' : 'Inadequate', 
'_/\,' : 'Inch Worm', 
':-S' : 'Incoherent', 
'(o_O)' : 'Incredulous', 
':7/' : 'Indecisive', 
':-|' : 'Indifferent', 
':-I' : 'Indifferent', 
'-' : 'Indifferent', 
'E_E' : 'Indifferent', 
':neutral:' : 'Indifferent', 
'**' : 'Infatuated', 
'(*)=3' : 'Infatuated', 
'()' : 'Infatuated', 
'0:-)' : 'Innocent', 
'O:D' : 'Innocent', 
'(wm)' : 'Innocent', 
')' : 'Insane', 
'?_?' : 'Irritated', 
'%7<' : 'Irritated', 
'(ip)' : 'Island with a Palm Tree', 
'^#(^' : 'It Was Not Me', 
'(wasntme)' : 'It Was Not Me', 
':<|' : 'Ivy League', 
'Emoticons' : 'that start with J', 
'Emoticon' : 'Meaning', 
'(:-|K-' : 'James Bond', 
'.().' : 'Jamming to music', 
'8(>_<)8' : 'Jealous', 
'8-)' : 'Joe Cool', 
'//o-o\\' : 'John Lennon', 
'((*J*))' : 'John Lennon', 
'.-' : 'John Lennon', 
'X-p' : 'Joking', 
'(jk)' : 'Joking', 
'*JOKINGLY*' : 'Jokingly', 
':-]' : 'Jovial', 
'\m/<(^_^)>\m/' : 'Joyful', 
'()/' : 'Joyful', 
'o(^o^)o' : 'Joyful', 
'()' : 'Joyful', 
'Emoticons' : 'that start with K', 
'Emoticon' : 'Meaning', 
'(:-#' : 'Keeping Quiet', 
'c",)' : 'Kid', 
'K:P' : 'Kid', 
'X:-)' : 'Kid', 
'\VVV/' : 'King', 
'\$$$/' : 'King', 
']:)|--<' : 'King', 
'<(^.^)>' : 'Kirby', 
"<('.'<)" : "Kirby",
"(>'.')>" : "Kirby",
'<(^_^)>' : 'Kirby', 
"<('.')>" : "Kirby",
"<('-'<)" : "Kirby",
"(>'')>" : "Kirby",
'c(-_-c)' : 'Kirby', 
'<(^,..,^)>' : 'Kirby', 
'(^^)' : 'Kirby', 
'*' : 'Kiss', 
':-)*' : 'Kiss', 
':-X' : 'Kiss', 
':-*' : 'Kiss', 
';-(!)' : 'Kiss', 
':*)' : 'Kiss', 
'8^*' : 'Kiss', 
':+' : 'Kiss', 
':P' : 'Kiss', 
':*' : 'Kiss', 
'X(*/*)x' : 'Kiss', 
'(3)' : 'Kiss', 
'(xo)' : 'Kiss', 
':-{}' : 'Kiss', 
'(^3^)' : 'Kiss', 
'(*^3^)/~' : 'Kiss', 
'(*^^)^*)' : 'Kiss', 
':=*' : 'Kiss', 
'(kiss)' : 'Kiss', 
'()`)' : 'Kiss', 
'(_X_)' : 'Kiss my Butt', 
'' : 'Kiss my butt', 
'*KISSED*' : 'Kissed', 
':}{:' : 'Kisses', 
'*KISSING*' : 'Kissing', 
'(}{)' : 'Kissing', 
'(-}{-)' : 'Kissing', 
':**:' : 'Kissing', 
'(=^-^=)' : 'Kitten', 
'=^.^=' : 'Kitty', 
'=+=' : 'Kitty', 
':3' : 'Kitty', 
'=^w^=' : 'Kitty', 
'(=^--^=)' : 'Kitty', 
'(=^^=)' : 'Kitty', 
'[|]' : 'Kleenex', 
'>>:-|' : 'Klingon', 
'.-=o=-.' : 'Klingon Bird of Prey', 
'+<#^v' : 'Knight', 
'+<||-)' : 'Knight', 
'@(*o*)@' : 'Koala', 
'' : 'Koala', 
'' : 'Koala', 
'' : 'Koala', 
':*)O' : 'Kool', 
'' : 'Kyubey', 
'Emoticons' : 'that start with L', 
'Emoticon' : 'Meaning', 
'&0(80<' : 'Lady', 
'<{::}>' : 'Ladybug', 
'(::)<' : 'Ladybug', 
'-.-' : 'Lame', 
'' : 'Larry David', 
'l8r)' : 'Later', 
':))' : 'Laughing', 
'XD' : 'Laughing', 
':L' : 'Laughing', 
":'D" : "Laughing",
'=^D' : 'Laughing', 
'>8-D' : 'Laughing', 
'(^_^)' : 'Laughing', 
'()' : 'Laughing', 
'-*)' : 'Laughing', 
':o' : 'Laughing', 
'' : 'Laughing', 
'' : 'Laughing', 
'=-D' : 'Laughing', 
'=D' : 'Laughing Out Loud', 
'X-D' : 'Laughing Out Loud', 
'(lol)' : 'Laughing Out Loud', 
':lol:' : 'Laughing Out Loud', 
':.-)' : 'Laughing Tears', 
'({)' : 'Left Hug', 
'()' : 'Lethargic', 
':^o' : 'Liar Liar', 
':PdPdP' : 'Licking', 
':-9' : 'Licking', 
'(`)' : 'Licking', 
'#-)' : 'Lieutenant LaForge', 
'(i)' : 'Light Bulb', 
'(li)' : 'Lightning', 
'(Y)' : 'Like', 
':3' : 'Lion', 
':-*' : 'Lips are Sealed', 
':-#' : 'Lips are Sealed', 
':-X' : 'Lips are Sealed', 
':X' : 'Lips are Sealed', 
':#' : 'Lips are Sealed', 
':=x' : 'Lips are Sealed', 
':=#' : 'Lips are Sealed', 
':()' : 'Lipstick', 
':-{}' : 'Lipstick', 
'd-_-b' : 'Listening to Music', 
'd^_^b' : 'Listening to Music', 
'd(^_^)b' : 'Listening to Music', 
'o(^_^)o' : 'Listening to music', 
'd(-\\\)b' : 'Listening to music', 
'_\\//' : 'Live Long and Prosper', 
'>-<' : 'Livid', 
'(.`.)' : 'Livid', 
'(**)' : 'Livid', 
'~~I==I>' : 'Lizard', 
'' : 'Lobster', 
'@---' : 'Lollipop', 
':P@---' : 'Lollipop', 
':~)' : 'Long Nose', 
'(*)?(*)' : 'Looking', 
'>_>' : 'Looking', 
'<_<' : 'Looking', 
'>.>' : 'Looking', 
'\\(<.<|>.>)//' : 'Looking', 
'(_)' : 'Looking', 
'<o?o>' : 'Looking at You', 
'<*_*>' : 'Looking at You', 
'L-)' : 'Loser', 
':-{}' : 'Lots of Lipstick', 
'<3' : 'Love', 
'~~' : 'Love', 
':x' : 'Love Struck', 
'__.' : 'Lying Down', 
'o@=<' : 'Lying Down', 
'Emoticons' : 'that start with M', 
'Emoticon' : 'Meaning', 
'=/' : 'Mad', 
'>=(' : 'Mad', 
'>,<' : 'Mad', 
'~:(' : 'Mad', 
'>=[' : 'Mad', 
'>}:-(' : 'Mad', 
':U' : 'Mad', 
')8^(' : 'Mad', 
':!' : 'Mad', 
">;-('" : "Mad",
'>_<' : 'Mad', 
':x' : 'Mad', 
':-x' : 'Mad', 
':mad:' : 'Mad', 
'(#)' : 'Mad', 
':-.)' : 'Madonna', 
'{8-*' : 'Maggie Simpson', 
'*)' : 'Magic Casting', 
'<*:-)' : 'Magician', 
'(malthe)' : 'Malthe', 
'0-|-[' : 'Man', 
'@@@@:-)' : 'Marge Simpson', 
'(@@@@):^)' : 'Marge Simpson', 
'######:o)' : 'Marge Simpson', 
'@@@:)' : 'Marge Simpson', 
'(#-[' : 'Marine', 
':-)(-:' : 'Married', 
'' : '', 
'' : 'Married', 
'-----(_)-' : 'Marshmallow', 
'-()_)()_)' : 'Marshmallow', 
'(.!.)' : 'Martian', 
'=:)' : 'Martian', 
'Q>--|' : 'Martini', 
'(d)' : 'Martini Glass', 
'|>--|' : 'Martini Glass', 
'(drink)' : 'Martini Glass', 
'>:-I' : 'Mean', 
'@|-)' : 'Meditating', 
'(-_-)' : 'Meditating', 
'' : 'Meh', 
'' : 'Mellow', 
'O' : 'O', 
'@' : 'Mention', 
'@_@' : 'Mesmerized', 
'\m/' : 'Metal', 
'lml' : 'Metal', 
'lml_' : 'Metal', 
'|:-[|]' : 'Mick Jagger', 
'8(:-)' : 'Mickey Mouse', 
'O' : 'Mickey Mouse', 
'o/<' : 'Midget', 
'(o:v)' : 'Miner', 
':p' : 'Mischievous', 
':}' : 'Mischievous', 
'?8}' : 'Mischievous', 
'=)=' : 'Mixed Feelings', 
':D:' : 'Mixed Feelings', 
'(mm)' : 'Mmm', 
'(mp)' : 'Mobile Phone', 
'^o^' : 'Mog', 
'-:-)' : 'Mohawk', 
"=.'v" : "Mohawk",
'(mo)' : 'Money', 
'[*(1)*]' : 'Money', 
'$-)' : 'Money Eyes', 
':-$' : 'Money Mouth', 
':-($)' : 'Money Mouth', 
'O|-)' : 'Monk', 
'+<:-|' : 'Monk', 
'@(-_-)@' : 'Monkey', 
':(|)' : 'Monkey', 
'U' : 'Monkey', 
"@('.')@" : "Monkey",
'---' : 'Monkey', 
"@'o'@" : "Monkey",
'@(^_^)@' : 'Monkey', 
'@(*_*)@' : 'Monkey', 
'()=' : 'Monkey', 
'(;_)' : 'Monocle', 
'_' : 'Monocle', 
':E' : 'Monster', 
"';..;'" : "Monster",
'VVV' : 'Monster', 
'>:(><)' : 'Monster', 
'(_i_)' : 'Mooning', 
'(mooning)' : 'Mooning', 
'(|)' : 'Mooning You', 
'(>|<)' : 'Mosquito', 
'o-7-o' : 'Motorbike', 
'o--7o' : 'Motorcycle', 
':o&o>' : 'Motorcycle', 
'^v^v^' : 'Mountain', 
'~<>^>' : 'Mouse', 
'oO~' : 'Mouse', 
'<:3)~' : 'Mouse', 
'<:3)~~' : 'Mouse', 
'<:3)~~~' : 'Mouse', 
'8(:-)' : 'Mouseketeer', 
'(~)' : 'Movie', 
'(film)' : 'Movie', 
'(movie)' : 'Movie', 
'(m)' : 'MSN Messenger', 
'cl_l' : 'Mug', 
'[II]D' : 'Mug', 
'(_)' : 'Mug', 
'(flex)' : 'Muscle', 
'(muscle)' : 'Muscle', 
'' : 'Muscular Person', 
'(music)' : 'Music', 
':-{' : 'Mustache', 
':{' : 'Mustache', 
'={D' : 'Mustache', 
':{D' : 'Mustache', 
':{)' : 'Mustache', 
':-#|' : 'Mustache', 
':-3' : 'Mustache', 
':{|' : 'Mustache Man', 
':-:' : 'Mutant', 
'(myspace)' : 'Myspace', 
'Emoticons' : 'that start with N', 
'Emoticon' : 'Meaning', 
':_:' : 'Nagato', 
':-SS' : 'Nailbiting', 
'(Z(:^P' : 'Napoleon', 
'~,~' : 'Napping', 
'_:^)' : 'Native American', 
':3' : 'Naughty Grin', 
'*:-)' : 'Navy Admiral', 
'@:-)' : 'Navy Captain', 
'#:-)' : 'Navy Commander', 
'=:-)' : 'Navy Lieutenant', 
'(-)' : 'Needs Haircut', 
'*8-I' : 'Nerd', 
':-B' : 'Nerd', 
'8-|' : 'Nerd', 
'8-B' : 'Nerd', 
':-=H' : 'Nerd', 
'B-|' : 'Nerd', 
'8|' : 'Nerd', 
'B|' : 'Nerd', 
'(nerd)' : 'Nerd', 
'8=|' : 'Nerd', 
'B=|' : 'Nerd', 
'|-(:-)' : 'Nerd', 
'[-_-]~' : 'Ninja', 
'Qx' : 'Ninja', 
'QK' : 'Ninja', 
'(j)' : 'Ninja', 
'(ninja)' : 'Ninja', 
'[+..]' : 'Nintendo Controller', 
'(nod)' : 'Nodding', 
'(' : 'Nodding', 
'(?_?)' : 'Nonsense', 
'):-(' : 'Nordic', 
'<:@0' : 'Nose', 
'(:^(' : 'Nose', 
'(:+)' : 'Nose', 
':/\)' : 'Nose', 
':v)' : 'Nose', 
'>*(' : 'Nose', 
'.^v' : 'Nose', 
'%-(' : 'Not Listening', 
'<2' : 'Not quite love', 
'[-(' : 'Not talking', 
'^:)^' : 'Not Worthy', 
'(8)' : 'Note', 
']:-)' : 'Nurse', 
'~=[,,_,,]:3' : 'Nyan Cat', 
'[^._.^]' : 'Nyan Cat', 
'||' : 'Nyan Cat', 
'Emoticons' : 'that start with O', 
'Emoticon' : 'Meaning', 
':' : 'Octopus', 
'O_o' : 'Oddball', 
':-j' : 'Oh Go On', 
'?:-_]' : 'Old Lady', 
'|:-{)~' : 'Old Man', 
'(-o-)' : 'Olympic Hammer Throw', 
':)]' : 'On the Phone', 
'' : 'On The Phone', 
'' : 'On The Phone', 
'()' : 'On The Phone', 
"':-(" : "One Eyebrow",
'=X' : 'Oops', 
'E:-)' : 'Operator', 
'~#|__/~~\o/~' : 'Overboard', 
'^_^' : 'Overjoyed', 
'.^_^.' : 'Overjoyed', 
':-)))' : 'Overweight', 
'^o,o^' : 'Owl', 
'-(*o*)-' : 'Owl', 
'(^o^)' : 'Owl', 
"--''--''--" : "Owl",
'-"-"-' : 'Owl', 
'^(OvO)^' : 'Owl', 
'' : 'Owl', 
'Emoticons' : 'that start with P', 
'Emoticon' : 'Meaning', 
':v' : 'Pacman', 
'(:V)' : 'Pacman', 
'(:\/)' : 'Pacman', 
'(V)=|' : 'Pacman Trophy', 
'(>_<)' : 'Painful', 
'(_)' : 'Painting', 
'8:(' : 'Panda', 
'(panda)' : 'Panda', 
'' : 'Panda', 
'\(>o<)/' : 'Panicking', 
'\\(<.<|>.>)//' : 'Panicking', 
'(>-:-)-<' : 'Parachute', 
'(@.@)' : 'Paranoid', 
'{|:{)' : 'Park Ranger', 
'<:-P' : 'Party', 
'<:o)' : 'Party', 
'<o)' : 'Party', 
'(party)' : 'Party', 
'*<(:)' : 'Party Hat', 
'<l:0' : 'Partying', 
'*<(8)~/~<' : 'Partying', 
'*<|8-P~' : 'Partying Too Much', 
'(:V' : 'Pato', 
':)>-' : 'Peace', 
'(/|\)' : 'Peace', 
'(^o^)y' : 'Peace', 
'*p*' : 'Peace', 
'(-)' : 'Peace', 
'..' : 'Peace', 
'(/)' : 'Peering', 
'<IIEEEEEED' : 'Pen', 
'0))__)>' : 'Pencil', 
'w' : 'Penguin', 
"('v')" : "Penguin",
'<(")' : 'Penguin', 
'<(^)' : 'Penguin', 
"<('')" : "Penguin",
'8>' : 'Penguin', 
'*-)' : 'Pensive', 
':-/' : 'Perplexed', 
'XP' : 'Perplexed', 
'_' : 'Perplexed', 
'<:^]' : 'Person', 
'O<-<' : 'Person', 
'>:P' : 'Phbbbbt', 
'-()' : 'Phew', 
':?)' : 'Philosopher', 
'(mp)' : 'Phone', 
'(ph)' : 'Phone', 
'(phone)' : 'Phone', 
'((()))' : 'Phone', 
'/_/_/_/_/' : 'Piano', 
'\___/' : 'Pie', 
'----|}' : 'Pie Being Thrown', 
'--===[}' : 'Pie Fight', 
'(~_(]=--Z()' : 'Pie Fight', 
'=8)' : 'Pig', 
'o()~' : 'Pig', 
':@)' : 'Pig', 
':(:)' : 'Pig', 
"<('@')>" : "Pig",
'`' : 'Pig', 
':=)' : 'Pig', 
'<(^oo^)>' : 'Pig', 
'^(*(oo)*)^' : 'Pig', 
'()' : 'Pig', 
'^..^__)~' : 'Pig', 
'(oo)' : 'Piggy', 
'/***(^o^)***\"' : 'Pigtails', 
"/~'v'~\'" : "Pigtails",
'(v)' : 'Pigtails', 
"^_^''" : "Pikachu",
'(o^-^o)' : 'Pikachu', 
'<(:-)' : 'Pilgrim', 
'(__)' : 'Pill', 
'(_)' : 'Pineapple', 
'' : 'Ping Pong table', 
':---)' : 'Pinnochio', 
':-------[' : 'Pinocchio', 
'b)' : 'Pirate', 
'P)' : 'Pirate', 
';PX' : 'Pirate', 
':ar!' : 'Pirate', 
'R)' : 'Pirate', 
'-=,q' : 'Pistol', 
'<%)' : 'Pizza', 
'(pi)' : 'Pizza', 
'<|' : 'Pizza', 
'(pizza)' : 'Pizza', 
'(pl)' : 'Plate', 
';T' : 'Playful', 
'\/' : 'Playing in the snow', 
'(+[__]:)' : 'PlayStation Portable', 
'(^^)' : 'Pleased', 
'(pu)' : 'Point Up', 
'O-G-<' : 'Pointing', 
'()' : 'Pointing', 
'' : 'Pointing', 
':-I' : 'Poker Face', 
'(*)(*O)' : 'Poking', 
'' : 'Polar bear', 
'-[[]]--[()]-' : 'Police Chase', 
'[|:-{O' : 'Police Officer', 
'c|:-|' : 'Police Officer', 
'()' : 'Pompous', 
'^' : '', 
'' : 'Poodle', 
'(poolparty)' : 'Pool Party', 
'(hrv)' : 'Pool Party', 
'~@~' : 'Poop', 
'+O=-)' : 'Pope', 
'+<:-)' : 'Pope', 
';-?' : 'Popeye', 
':<' : 'Pout', 
'>:-[' : 'Pouting', 
':-\"' : 'Pouting', 
'\o/' : 'Praise The Lord', 
'O/' : 'Praise The Lord', 
'_/\_' : 'Prayer', 
"/\'s" : "Prayers",
'[-o<' : 'Praying', 
'_/\_' : 'Praying', 
'_|' : 'Praying', 
'(*)' : 'Praying', 
'' : 'Precious', 
'&' : 'Pretzel', 
'+:-)' : 'Priest', 
'(zilmer)' : 'Priidu', 
'\<><>/' : 'Prince', 
'O(+>' : 'Prince', 
'~<:-)' : 'Princess', 
'\&&&/' : 'Princess', 
':}' : 'Princess', 
'@(*-*)@' : 'Princess Leia', 
'x{|:)' : 'Propeller Hat', 
'-' : 'Proud', 
'(+[PSP]::)' : 'PSP', 
'' : 'Psycho', 
'*3' : 'Pucker up', 
':&' : 'Puke', 
'(puking)' : 'Puking', 
'(^:^)' : 'Pumpkin', 
'(~~)' : 'Pumpkin', 
'*|' : 'Punch', 
'(_)' : 'Punched', 
'(punch)' : 'Punching', 
'(o(o' : 'Punching', 
'=(-_-' : 'Punching', 
'0()=' : 'Punching', 
'(o)=)`)' : 'Punching', 
'()=)-)' : 'Punching', 
'-:-/' : 'Punk', 
'UU' : 'Puppy', 
'__' : 'Puppy Love', 
"Q('.'Q)" : "Put Em Up",
'()' : 'Puzzled', 
'Emoticons' : 'that start with Q', 
'Emoticon' : 'Meaning', 
'C):-' : 'O', 
'C):-' : 'O', 
'C):-' : 'O', 
'C):-O' : 'Quartet', 
'\%%%/' : 'Queen', 
':?:' : 'Question', 
'Emoticons' : 'that start with R', 
'Emoticon' : 'Meaning', 
'>-=]' : 'Rabbit', 
"('.')" : "Rabbit",
'(")_(")' : 'Rabbit', 
'(uu)' : 'Rabbit', 
'8:3' : 'Rabbit', 
'`=o=^o>' : 'Race Car', 
'CD:-)>' : 'Railroad Worker', 
'~~:-(' : 'Rain', 
'(rain)' : 'Rain', 
'(london)' : 'Rain', 
'(R)' : 'Rainbow', 
'/:)' : 'Raised Eyebrow', 
'd:o)' : 'Rapper', 
'=:7)~~' : 'Rat', 
'=:7(~~' : 'Rat', 
'(((((:-{=' : 'Raver', 
'_' : 'Raving', 
'(l)' : 'Red Heart', 
'(k)' : 'Red Lips', 
'(f)' : 'Red Rose', 
'}---:o>' : 'Reindeer', 
'o(^)o' : 'Reluctant', 
'~o)' : 'Reproduction', 
'>=D' : 'Revenge', 
'?$?:-)' : 'Rich', 
'(})' : 'Right Hug', 
'/O' : 'Rimshot', 
'(_)' : 'Ringo Starr', 
'________' : 'Road', 
'*<l:o)>' : 'Robin Hood', 
'([(' : 'Robocop', 
'[*.*]' : 'Robot', 
':|]' : 'Robot', 
':]' : 'Robot', 
':]]' : 'Robot', 
'[:]' : 'Robot', 
'<(-_-)>' : 'Robot', 
'~(o_o)~' : 'Robot', 
'[:|]' : 'Robot', 
'\m/(**)\m/' : 'Rock On', 
'\m/@_@\m/' : 'Rock On', 
'\m/>.<\m/' : 'Rocker', 
'\m/(><)\m/' : 'Rocker', 
'd(>_<)b' : 'Rocker', 
'\m/(>.<)\m/' : 'Rocker', 
'bd(OoO)bd' : 'Rocker', 
'<:-)<<|' : 'Rocket', 
'<===~~' : 'Rocket', 
'\w/^^,\w/' : 'Rocking', 
'>-D' : 'Rocking', 
'\m/' : 'Rocking', 
'\\m/(=o+)\m//' : 'Rocking', 
'(rock)' : 'Rocking', 
'\m/(*o*)\m/' : 'Rocking Out', 
'\m/d(^_^)b\m/' : 'Rocking Out', 
'8-|' : 'Rolling Eyes', 
'>>' : 'Rolling Eyes', 
'9_9' : 'Rolling Eyes', 
'@@' : 'Rolling Eyes', 
'c.c' : 'Rolling Eyes', 
':roll:' : 'Rolling Eyes', 
'' : 'Rolling Eyes', 
'=))' : 'Rolling on the Floor Laughing', 
'(rotfl)' : 'Rolling on the Floor Laughing', 
'(rofl)' : 'Rolling on the Floor Laughing', 
'()' : 'Romantic', 
'7:-)' : 'Ronald Reagan', 
'\:)' : 'Ronald Reagan', 
'~:>' : 'Rooster', 
'^:3' : 'Rooster', 
'@)->-' : 'Rose', 
'@~)~~~~' : 'Rose', 
'@}->--' : 'Rose', 
'@};-' : 'Rose', 
"@~'~~~" : "Rose",
'@>-;--' : 'Rose', 
'@-->---' : 'Rose', 
'--{--@' : 'Rose', 
'@>--' : 'Rose', 
'@}-^--^--' : 'Rose', 
'(@)->->->--' : 'Rose', 
'@}-(' : 'Rose', 
'<(*_*)>' : 'Rosie', 
'3:*>' : 'Rudolf', 
'(;_)' : 'Running', 
'=()' : 'Running', 
'' : 'Running', 
'=(;)' : 'Running', 
'Emoticons' : 'that start with S', 
'Emoticon' : 'Meaning', 
'=(' : 'Sad', 
':-(' : 'Sad', 
':(' : 'Sad', 
'T.T' : 'Sad', 
'=[' : 'Sad', 
':c' : 'Sad', 
'D:' : 'Sad', 
'D=' : 'Sad', 
'Y_Y' : 'Sad', 
'-' : 'Sad', 
'v.v' : 'Sad', 
'\8^1' : 'Sad', 
'(<_>)' : 'Sad', 
'(/_\)' : 'Sad', 
'):' : 'Sad', 
'(_)' : 'Sad', 
':[' : 'Sad', 
':sad:' : 'Sad', 
':=(' : 'Sad', 
'(sad)' : 'Sad', 
'8-(' : 'Sad', 
'/:-)' : 'Sailor', 
';-)}<////>' : 'Salesman', 
'>>>>(:-)' : 'Salesman', 
'M:-)' : 'Salute', 
'O7' : 'Salute', 
':-{o' : 'Salvador Dali', 
'*<]:{)' : 'Santa', 
'*<(:-{)}' : 'Santa', 
'*<:-)' : 'Santa Claus', 
'*<|:-{)}' : 'Santa Claus', 
'<|:)}' : 'Santa Claus', 
'0<[]:-)>>' : 'Santa Claus', 
'*-={:-)}}}>' : 'Santa Claus', 
'*<|:o)>' : 'Santa Claus', 
'<[]:o{|>' : 'Santa Claus', 
'*<[]:o{|>' : 'Santa Claus', 
':-7' : 'Sarcastic', 
'^o)' : 'Sarcastic', 
';s' : 'Sarcastic', 
':S' : 'Sarcastic', 
'D:' : 'Scared', 
':!' : 'Scared', 
'(;)' : 'Scared', 
'.()' : 'Scared', 
'()' : 'Scaring', 
'()' : 'Scary', 
'' : 'Scheming', 
'*!#*!^*&:-)' : 'Schizophrenic', 
'!:-)' : 'Scholar', 
'*s*' : 'School', 
'8<' : 'Scissors', 
'c--I-I-I{' : 'Scorpion', 
'3#`' : 'Scorpion', 
'>-$' : 'Scowling', 
'^:-/' : 'Scratching Head', 
':-@' : 'Screaming', 
'..._[:]' : 'Scuba Diver', 
'..._(:)-o' : 'Scuba Diver', 
'O-)' : 'Scuba Diver', 
'(:)-)' : 'Scuba Diver', 
"\';./" : "Sea Horse",
'' : 'Seal', 
'()' : 'Seal', 
';^!' : 'Secret', 
':-*' : 'Secret Telling', 
'8==8' : 'Seeing Eye to Eye', 
'\000/' : 'Shaka', 
'(shake)' : 'Shaking', 
'9(x.x)9' : 'Shaking Fist', 
'(x.x)9' : 'Shaking Fist', 
'[-x' : 'Shame on You', 
'<(((">' : 'Shark', 
'(^^^)' : 'Shark', 
'~~~/\\~~~' : 'Shark', 
'>---^-*<' : 'Shark', 
'_/\____\0/__' : 'Shark', 
'_/\_\o/_' : 'Shark Attack', 
'=O' : 'Shocked', 
'*SHOCKED*' : 'Shocked', 
'o_o' : 'Shocked', 
':-o' : 'Shocked', 
'8-0' : 'Shocked', 
'o' : 'Shocked', 
'O' : 'Shocked', 
'8^{}' : 'Shocked', 
'(O_O)' : 'Shocked', 
'8O' : 'Shocked', 
':shock:' : 'Shocked', 
'(**)' : 'Shocked', 
'' : 'Shocked', 
'=(.)=r' : 'Shooting', 
'()o*--' : 'Shooting', 
'()*' : 'Shooting', 
'' : 'Shooting Star', 
'^^' : 'Shoulder Shrug', 
':-V' : 'Shouting', 
':\/' : 'Shouting', 
'|----D' : 'Shovel', 
"`\('_')/`" : "Shrug",
'\(_)/' : 'Shrugging', 
'\_()_/' : 'Shrugging', 
'(*^_^*)' : 'Shy', 
'-_-' : 'Shy', 
'(^^;)' : 'Shy', 
'(#^.^#)' : 'Shy', 
'(#/\#)' : 'Shy', 
'(*)' : 'Shy', 
'(-:|:-)' : 'Siamese Twins', 
':-&' : 'Sick', 
'+o(' : 'Sick', 
'|-~b' : 'Sick', 
'(-__-)' : 'Sick', 
':-~)' : 'Sick', 
':->|' : 'Sick', 
':-Y' : 'Side Comment', 
':-<' : 'Sigh', 
'8-}' : 'Silly', 
'=P' : 'Silly', 
'C(:' : 'Silly', 
'(^o^)' : 'Singing', 
':-o' : 'Singing', 
'(o)~' : 'Singing', 
']:' : 'Skateboard', 
'O-\-<]:' : 'Skateboarder', 
'0-<-<):' : 'Skateboarder', 
'o{-<]:' : 'Skateboarder', 
'O[-<]:' : 'Skateboarder', 
'o<[^(' : 'Skater', 
'o->-</:' : 'Skater', 
'q=)-<--<|:' : 'Skater', 
'O-/-<]:' : 'Skater', 
':-/' : 'Skeptical', 
':-7' : 'Skeptical', 
':/' : 'Skeptical', 
'(.)' : 'Skeptical', 
'*(H-)' : 'Skier', 
'=(^-^)' : 'Skipping', 
'8-X' : 'Skull', 
'(skype)' : 'Skype', 
'(ss)' : 'Skype', 
'(^^)(o)' : 'Slapping', 
'(>.<)' : 'zzZ Sleeping', 
'-_-' : 'Sleeping', 
'-_-' : 'Zzzzz Sleeping', 
'(-.-)zzZZ' : 'Sleeping', 
'Z/' : 'Sleeping', 
'Z_Z' : 'Sleeping', 
'Q' : 'Q', 
'-' : 'Sleeping', 
'(~_~)^' : 'Sleeping', 
'(-_o)zzZ' : 'Sleeping', 
'O-(==<' : 'Sleeping', 
'<-.->' : 'Sleeping', 
'(--)zzz...' : 'Sleeping', 
'' : 'Sleeping', 
'|-)' : 'Sleepy', 
'(>.<)' : 'Sleepy', 
'u_u' : 'Sleepy', 
'#)' : 'Sleepy', 
'"8^y' : 'Sleepy', 
'~_~' : 'Sleepy', 
'(-_-)Zzz' : 'Sleepy', 
'(Z.Z)' : 'Sleepy', 
'I-)' : 'Sleepy', 
'(snooze)' : 'Sleepy', 
'I=)' : 'Sleepy', 
"#(,'%/)" : "Slept Too Long",
':-#' : 'Smacked', 
':-)' : 'Smile', 
':)' : 'Smile', 
'o,' : 'o', 
'\_/' : 'Smile', 
'[______]' : 'Smile', 
':|)' : 'Smile', 
'C:' : 'Smile', 
'\\)' : 'Smile', 
':A' : 'Smile', 
':)' : 'Smile', 
'=]' : 'Smile', 
'\__/' : 'Smile', 
'(*8' : 'Smile', 
'I:(' : 'Smile', 
'>-)' : 'Smile', 
':^D' : 'Smile', 
':]' : 'Smile', 
':smile:' : 'Smile', 
':=)' : 'Smile', 
'(smile)' : 'Smile', 
'()' : 'Smile', 
':^J' : 'Smiling', 
'^^' : 'Smiling', 
'^&^' : 'Smiling', 
".'J" : "Smiling",
':-1' : 'Smirk', 
':-,' : 'Smirk', 
':^,' : 'Smirking', 
';^)' : 'Smirking', 
'(smirk)' : 'Smirking', 
'()' : 'Smitten', 
':-p~' : 'Smoker', 
':-d~' : 'Smoker', 
':-Q' : 'Smoking', 
':O\"' : 'Smoking', 
':-' : 'i Smoking', 
':-?' : 'Smoking', 
':-d' : 'Smoking', 
':-G-' : 'Smoking', 
'(--)y-' : 'Smoking', 
'(())y-' : 'Smoking', 
'(smoke)' : 'Smoking', 
'(smoking)' : 'Smoking', 
'(ci)' : 'Smoking', 
'o()y' : 'Smoking', 
':-?' : 'Smoking a Pipe', 
'(`)' : 'Smooch', 
':>' : 'Smug', 
'B|' : 'Smug', 
'(sn)' : 'Snail', 
'@x' : 'Snail', 
'_@/' : 'Snail', 
'`@____' : 'Snail', 
'@_v' : 'Snail', 
'@_' : 'Snail', 
'_@_v' : 'Snail', 
'"' : 'Snail', 
'_@v' : 'Snail', 
'~<:<<<<<>' : 'Snake', 
'~~~~8}' : 'Snake', 
'~>)' : 'Snake', 
':-`|' : 'Sniffling', 
':<)' : 'Snobby', 
'(_' : 'Snooper', 
'|^O' : 'Snoring', 
'^o' : 'Snoring', 
'' : 'Snowing', 
'(:^)_)_)' : 'Snowman', 
'[l:^)' : 'Snowman', 
'(:-)()' : 'Snowman', 
'*|:^)(.)(...)' : 'Snowman', 
'(`)' : 'Snubbing', 
'(A`)' : 'Snubbing', 
'' : 'O', 
'D' : '', 
'' : 'O So Wrong', 
'.`(><)`.' : 'Sobbing', 
'(so)' : 'Soccer Ball', 
'(____)' : 'Sock', 
'/:-)' : 'Soldier', 
'c]:{D' : 'Sombrero', 
'' : 'Sonic the Hedgehog', 
'?-(' : 'Sorry', 
'=^{' : 'Sorry', 
'>.<' : 'Sour', 
':-*' : 'Sour', 
':-6' : 'Sour', 
'(X^(*' : 'Sour Face', 
'X' : 'P Sour Face', 
'=.=' : 'Sour Face', 
'[>==]' : 'South African Flag', 
'0_o' : 'Spaced Out', 
'|-=[O]=-|' : 'Spaceship', 
':-M' : 'Speak no Evil', 
'=#' : 'Speechless', 
':|' : 'Speechless', 
':-|' : 'Speechless', 
':=|' : 'Speechless', 
'(speechless)' : 'Speechless', 
'o' : 'O', 
'||||' : 'Spider', 
'/\(00)/\"' : 'Spider', 
'' : 'Spider', 
'^;;^' : 'Spider', 
'::::(' : 'Spider', 
':-`' : 'Spitting', 
'>:-I' : 'Spock', 
'_' : 'Spooked', 
'===()' : 'Sprinting', 
'__m_OO_m__' : 'Spy', 
'<:' : 'Squid', 
'' : 'Squid', 
'(><)' : 'Squinting', 
'-_-' : 'Squinting', 
'(*)' : 'Star', 
'(star)' : 'Star', 
'*~*' : 'Star Gazed', 
'' : 'Staring', 
'(;_)' : 'Staring', 
'()' : 'Staring', 
'%.)' : 'Staring at a Screen for Too Long', 
'=-O' : 'Starship Enterprise', 
'(~);}' : 'Stealie', 
';@' : 'Steaming Mad', 
'||=||' : 'Stereo', 
'|:-|' : 'Stern', 
'' : 'O', 
'/\"' : 'Stick Man', 
'' : 'O', 
'#:-)-{--<' : 'Stick Man', 
'>-/-@' : 'Stick Man', 
'O-[--<' : 'Stickfigure', 
':-)~' : 'Sticking Tongue Out', 
':-P' : 'Sticking Tongue Out', 
':P' : 'Sticking Tongue Out', 
'>:P' : 'Sticking Tongue Out', 
':-r' : 'Sticking Tongue Out', 
':pp' : 'Sticking Tongue Out', 
':(,)' : 'Sticking Tongue Out', 
'(:-p)' : 'Sticking Tongue Out', 
'' : 'Sticking Tongue Out', 
".'r" : "Sticking Tongue Out",
':razz:' : 'Sticking Tongue Out', 
':=P' : 'Sticking Tongue Out', 
'(tongueout)' : 'Sticking Tongue Out', 
'~/~' : 'Stirring', 
'$:-$' : 'Stock Broker', 
'>;D' : 'Stoked', 
'*STOP*' : 'Stop', 
'(st)' : 'Stormy Cloud', 
':|' : 'Straight face', 
".'T" : "Straight Face",
'-.-' : 'Stressed', 
'O=[O{|___|]=O' : 'Stretcher', 
'@?@' : 'Stunned', 
'[o].[o]' : 'Stunned', 
'&;-P' : 'Suave', 
'(sun)' : 'Sun', 
'8-)' : 'Sunglasses', 
'B-)' : 'Sunglasses', 
'B-D' : 'Sunglasses', 
']-I' : 'Sunglasses', 
'B:-)' : 'Sunglasses', 
'8-|' : 'Sunglasses', 
'8|' : 'Sunglasses', 
'B-|' : 'Sunglasses', 
'B|' : 'Sunglasses', 
'8)' : 'Sunglasses', 
':cool:' : 'Sunglasses', 
'c-oo' : 'Sunglasses', 
'_\|/_' : 'Sunset', 
'(#)' : 'Sunshine', 
'((o))' : 'Sunshine', 
':o' : 'Surprised', 
':-O' : 'Surprised', 
'*SURPRISED*' : 'Surprised', 
':O' : 'Surprised', 
'{:o' : 'Surprised', 
'(:)o)' : 'Surprised', 
'O-' : 'O', 
'U' : 'Surprised', 
':-()' : 'Surprised', 
'=0' : 'Surprised', 
'G' : 'G', 
'-' : 'Surprised', 
'-' : 'Surprised', 
'(*.*)' : 'Surprised', 
'l8^O' : 'Surprised', 
'****' : 'Surprised', 
'0' : 'Surprised', 
'' : 'Surprised', 
'*_*' : 'Surprised', 
':eek:' : 'Surprised', 
':=o' : 'Surprised', 
'(surprised)' : 'Surprised', 
'*.*' : 'Surprised', 
'(O.O)' : 'Surprised', 
'=^o' : 'Surprised', 
'=^0' : 'Surprised', 
'' : 'Surrender', 
'' : 'O Suspicious', 
'' : 'Suspicious', 
':#' : 'Swearing', 
'>:-@!' : 'Swearing', 
'(swear)' : 'Swearing', 
'`:-)' : 'Sweating', 
'(:|' : 'Sweating', 
'(sweat)' : 'Sweating', 
'8-)' : 'Swimmer', 
'__/\o_' : 'Swimming', 
'B-)-[<' : 'Swimming Trunks', 
'x_O' : 'Swollen Eye', 
'/________|___|' : 'Sword', 
'oxx:{}:::::::>' : 'Sword', 
'cxxx{}:::::::>' : 'Sword', 
'0]xxxx]====>' : 'Sword', 
'<=======|==o' : 'Sword', 
'(>_)(_<)' : 'Sword Fighting', 
'---(|||]==[]' : 'Syringe', 
'+=>-' : 'Syringe', 
'Emoticons' : 'that start with T', 
'Emoticon' : 'Meaning', 
'/(..)' : 'Table Flips You', 
'(>o<)' : 'Table Tennis', 
'=;' : 'Talk to the Hand', 
':^y' : 'Talking', 
':y' : 'Talking', 
'(talk)' : 'Talking', 
'(____)' : 'Tank', 
'|"""\-=' : '', 
'(____)' : 'Tank', 
'>8-O-(&)' : 'Tapeworm', 
'()' : 'Tasty', 
'(tuari)' : 'Tauri', 
'\_/?' : 'Tea Cup', 
'C(_)~' : 'Teapot', 
"C(_)~'" : "Teapot",
':p' : 'Teasing', 
'B^P' : 'Teasing', 
':^P' : 'Teasing', 
'8^P' : 'Teasing', 
':O)' : 'Teddy Bear', 
'()' : 'Teddy Bear', 
'(t)' : 'Telephone Receiver', 
'(((((^_^)' : 'Teleporting', 
'-(:)(0)=8' : 'Teletubby', 
'>[I' : 'Television', 
'ixxxxxi' : 'Tennis Net', 
'|B-)' : 'Terminator', 
'-:}' : 'The Grinch', 
'8=:-K' : 'The Swedish Chef', 
':-?' : 'Thinking', 
'*-)' : 'Thinking', 
':?' : 'Thinking', 
':=?' : 'Thinking', 
'(think)' : 'Thinking', 
'(*_)*' : 'Throwing Away', 
'(n)' : 'Thumbs Down', 
"q('-')p" : "Thumbs Down",
':-q' : 'Thumbs Down', 
'(no)' : 'Thumbs Down', 
'(y)' : 'Thumbs Up', 
"d'-'" : "Thumbs Up",
"d'-'b" : "Thumbs Up",
':-bd' : 'Thumbs Up', 
'(^-^)b' : 'Thumbs Up', 
'd-(^.^)z' : 'Thumbs Up', 
'(ok)' : 'Thumbs Up', 
'(yes)' : 'Thumbs Up', 
'_' : 'Thumbs Up', 
':-)<////>' : 'Tie', 
'|-(o)-|' : 'TIE Fighter', 
'(-o-)' : 'TIE Fighter', 
'|o|' : 'TIE Fighter', 
'o' : '', 
'o' : 'Tigger', 
':-T' : 'Tight Lipped', 
'[]---|<O---[]' : 'Tight Rope', 
'(o)' : 'Time', 
'(time)' : 'Time', 
'(clock)' : 'Time', 
':-t' : 'Time Out', 
'-<:-(' : 'Tin Man', 
'(:|' : 'Tired', 
'*TIRED*' : 'Tired', 
'=_=' : 'Tired', 
'%-|' : 'Tired', 
'%-/' : 'Tired', 
'(z_z~.)' : 'Tired', 
'()' : 'Tired', 
'_' : 'Tired', 
'(=_=)' : 'Tired', 
'(%]:D' : 'Toad', 
'0000(0)(0)0000' : 'Toes', 
'.oooO' : 'Toes', 
'Oooo.' : 'Toes', 
'(toivo)' : 'Toivo', 
".'w" : "Tongue",
'8-;)' : 'Tongue in Cheek', 
':-J' : 'Tongue in Cheek', 
':j' : 'Tongue in Cheek', 
':-&' : 'Tongue Tied', 
':-a' : 'Tongue Touching Nose', 
'(tmi)' : 'Too Much Information', 
'[|:)' : 'Top Hat', 
'#:o\:o/:o\:o/:o||' : 'Totem Pole', 
"=')" : "Touched",
'{(:-)' : 'Toupee', 
'}:-(' : 'Toupee', 
'{:-)' : 'Toupee', 
'-HHHH' : 'Tower', 
'[..]' : 'Transformer', 
'>~<' : 'Translate', 
'>:-|' : 'Trekkie', 
':<()' : 'Tribesman', 
'---(o__)o' : 'Tripping', 
'(>_<)>' : 'Troubled', 
'(^_^;)' : 'Troubled', 
'<.<' : 'Troublemaker', 
'__' : '', 
'' : 'O    O Truck', 
'oo---oo-Bo' : 'Truck', 
'-=iii=<()' : 'Trumpet', 
'(_)' : 'Tuba', 
'O>-O>-|-<O-<O' : 'Tug of War', 
'X:-|' : 'Tupac Shakur', 
'@=)' : 'Turban', 
'@:-v' : 'Turban', 
'<:>==' : 'Turkey', 
'mm' : '', 
'' : 'l   L Turkey', 
'=8>-()<' : 'Turkey', 
'(tu)' : 'Turtle', 
':(' : 'Turtle', 
'/Y\"' : 'Tuxedo', 
':-)8---' : 'Tuxedo', 
':-)8>' : 'Tuxedo', 
'Emoticons' : 'that start with U', 
'Emoticon' : 'Meaning', 
'.-=-.' : 'UFO', 
'(o|o)' : 'Ultraman', 
'(um)' : 'Umbrella', 
'(---,' : 'Umbrella', 
'q;|' : 'Umpire', 
'x:-/' : 'Uncertain', 
'=l:-)=' : 'Uncle Sam', 
'=):-)>' : 'Uncle Sam', 
':-\"' : 'Undecided', 
':\"' : 'Undecided', 
'/:-|' : 'Undecided', 
':<' : 'Unhappy', 
'|:-)' : 'Unibrow', 
'|:' : 'Unimpressed', 
'' : 'Unimpressed', 
'**==' : 'United States Flag', 
">->'" : "Unsure",
':/' : 'Unsure', 
'8-\"' : 'Unsure', 
'>.<' : 'Upset', 
'}:(' : 'Upset', 
'>:*' : 'Upset', 
'D:<' : 'Upset', 
'>=P' : 'Upset', 
'>-:O' : 'Upset', 
'--"' : 'Upset', 
'.-.' : 'Upside Down', 
'P:' : 'Upward Lick', 
'Emoticons' : 'that start with V', 
'Emoticon' : 'Meaning', 
':-E' : 'Vampire', 
"(';.;')" : "Vampire",
'@,.,@' : 'Vampire', 
'*,..,*' : 'Vampire', 
'-,..,-' : 'Vampire', 
':-{' : 'Vampire', 
':f' : 'Vampire', 
"',..,'" : "Vampire",
'(o,..,o)' : 'Vampire', 
'(=,..,=)' : 'Vampire', 
':-[' : 'Vampire', 
':(=' : 'Vampire', 
'8-E' : 'Vampire', 
'>:-E' : 'Vampire', 
'>8-E' : 'Vampire', 
'>:-[' : 'Vampire', 
'8-{' : 'Vampire', 
'>8-{' : 'Vampire', 
':-[' : 'Vampire Bat', 
':[' : 'Vampire Bat', 
'^,..,^' : 'Vampire Bat', 
'^,..,^' : 'Vampire Bat', 
'~;;~' : 'Vampire Bat', 
'(^-^:)' : 'Vampire Bite', 
':-[' : 'Vampiro', 
'%*}' : 'Very Drunk', 
'=D' : 'Very Happy', 
':-))' : 'Very Happy', 
':-((' : 'Very Sad', 
'(o^_^)o' : 'Victory', 
'v(^_^)v' : 'Victory', 
'()' : 'Victory', 
'8<' : 'Video Projector', 
'](-[3' : 'Viking', 
'(o\_!_/o)' : 'Volkswagen Bug', 
'(o^)/(^o)' : 'Volleyball', 
'' : 'o', 
'ixxxxxxx' : 'i', 
':O=' : 'Vomit', 
':-C..' : 'Vomiting', 
'Emoticons' : 'that start with W', 
'Emoticon' : 'Meaning', 
"(>'.')>#" : "Waffle",
"(>'_')>#" : "Waffle",
'#<(0.0<)' : 'Waffle', 
'(o*)' : 'Wait', 
'(wait)' : 'Wait', 
'(((((((`)' : 'Wait', 
'(_)' : 'Wait', 
':->X==|' : 'Waiter', 
'_()' : 'Waiter', 
':-w' : 'Waiting', 
':3=' : 'Walrus', 
'(:{C)' : 'Walrus', 
':-<' : 'Walrus', 
'(:3=' : 'Walrus', 
'._)' : 'Warping', 
'-' : 'Watching', 
'__/\o_' : 'o Water Polo', 
':-h' : 'Wave', 
'(wave)' : 'Wave', 
'(hi)' : 'Wave', 
'(bye)' : 'Wave', 
'~~c___' : 'Waves', 
':-)--' : 'Weakling', 
'(~`)' : 'Weary', 
';w;' : 'Weeping', 
'(;`)' : 'Weeping', 
'(><)' : 'Weeping', 
':-P' : 'Whatever', 
'-_-' : 'Whatever', 
':-1' : 'Whatever', 
'(_)' : 'Whatever', 
'(_)' : 'Whatever', 
'.' : 'Whatever', 
'd-:' : 'Whatever', 
'#:-S' : 'Whew', 
'(whew)' : 'Whew', 
":'(" : "Whining",
":'-(" : "Whining",
'*WHINING*' : 'Whining', 
'(`)' : 'Whispering', 
':-"' : 'Whistling', 
".'Y" : "Whistling",
'()' : 'Whistling', 
'()' : 'Whoops', 
'(w)' : 'Wilted Rose', 
'' : 'Windows', 
'())=(' : 'Wine Glass', 
';p' : 'Wink', 
';-P' : 'Wink', 
';^)' : 'Wink', 
'(`_^)' : 'Wink', 
',-)' : 'Wink', 
'(^_~)' : 'Wink', 
'9-)' : 'Wink', 
'6-)' : 'Wink', 
'i)' : 'Wink', 
'!)' : 'Wink', 
';-)' : 'Winking', 
';)' : 'Winking', 
'~_^' : 'Winking', 
'U' : 'Winking', 
';()' : 'Winking', 
':wink:' : 'Winking', 
';=)' : 'Winking', 
'(wink)' : 'Winking', 
'' : 'Winking', 
'(^)' : 'Winking', 
'!-)' : 'Winking', 
'(-!' : 'Winking', 
'^_^a' : 'Wiping Tears', 
'' : 'Wiping Tears', 
'<):^/' : 'Witch', 
'___' : 'Witch', 
'<|:~,' : 'Witch', 
'I8${}' : 'Witch Doctor', 
'8<:-)' : 'Wizard', 
'<{{{};->~' : 'Wizard', 
'<*(:-?' : 'Wizard', 
'(-).*' : 'Wizard', 
'{0-|<[' : 'Woman', 
'o>-<|=' : 'Woman', 
'o.o?' : 'Wondering', 
':^)' : 'Wondering', 
'(wonder)' : 'Wondering', 
'||' : 'Woody Allen', 
'(wo)' : 'Work', 
':-S' : 'Worried', 
'~' : 'Worried', 
'(;)' : 'Worried', 
'>w<' : 'Worried', 
':S' : 'Worried', 
':=S' : 'Worried', 
'(worry)' : 'Worried', 
'' : 'Worried', 
'(`)' : 'Worried', 
'()' : 'Worried', 
'()' : 'Worshiping', 
'(_;)' : 'Writing', 
'()' : 'Writing', 
'Emoticons' : 'that start with X', 
'Emoticon' : 'Meaning', 
'(xx)' : 'Xbox', 
'[x]' : 'Xbox', 
'Emoticons' : 'that start with Y', 
'Emoticon' : 'Meaning', 
'_/)' : 'Yacht', 
'|-O' : 'Yawn', 
'(:|' : 'Yawn', 
".'U" : "Yawn",
'(yawn)' : 'Yawning', 
'(;`)' : 'Yawning', 
'*\o/*' : 'Yay', 
'>:O' : 'Yelling', 
'=^Y' : 'Yelling', 
':-(0)' : 'Yelling', 
':(*)' : 'Yelling', 
'(*O)' : 'Yelling', 
'(__)' : 'Yikes', 
'(%)' : 'Yin Yang', 
'\(o/' : 'Yin Yang', 
'<(-_-)>' : 'Yoda', 
'<(-.-)>' : 'Yoda', 
':-0>' : 'Yuck Face', 
'()' : 'Yummy', 
'Emoticons' : 'that start with Z', 
'Emoticon' : 'Meaning', 
':#' : 'Zip It', 
'F(x_x)F' : 'Zombie', 
'8-#' : 'Zombie', 
'[-]' : 'Zombie', 
'Z' : 'Zorro', 
'B-)===>' : 'ZZ Top', 
}