stop_words_list = ["hey", "hi", "a", "abhi", "abt", "ahh", "an", "and", "anybudy", "are", "as", "at",
              "aty", "aur", "aya", "b", "b4", "batao", "be", "because", "boss", "busy", "but", "by",
              "cacel", "can", "chat", "chrck", "chuck", "cme", "cool", "dat", "definitely", "den", "der",
              "dese", "did", "dis", "do", "does", "doing", "don", "don", "during", "each", "enjoy",
              "faq", "fate ", "few", "fine", "fo", "for", "for", "fr",
              "further", "fyi", "g", "gd", "gimme", "gm", "gn", "grateful", "grt", "gt", "had", "hai",
              "he", "her", "here", "hers", "herself", "him", "himself", "his", "hlp", "hmm", "ho", "hope", "hw",
              "i", "i'll", "if", "imedtly", "in", "into", "is", "it", "its", "itself", "ji", "just", "juz",
              "kal", "kno", "koi", "konsi", "kr", "krne", "laters", "lhl", "like", "little", "lol", "luck ",
              "luk", "m", "ma'am", "madam", "mera ", "moment", "most", "me", "my",
              "myself", "n", "na", "neva", "nhi", "nor", "ny", "nyc", "o", "of", "oh", "ohh", "oj", "on",
              "once", "only", "oops", "or", "our", "ours", "ourselves", "out", "over", "own", "pl",
              "please", "prose's", "r", "rs", "ru", "s", "sd", "she", "should", "shuld", "sir",
              "so", "some", "such", "t", "task", "tat", "tc", "temme", "tha", "than", "thankd", "that",
              "that's", "the", "theek", "their", "their", "theirs", "them", "themselves", "then",
              "these", "they", "this", "thiz", "those", "thr", "tht", "too", "tq",
              "true", "try", "ttyl", "tym", "ua", "very", "vil", "was", "wc", "we", "were", "while",
              "will", "with", "y", "yet", "yourself", "yourselves", "you", "pls", "have", "has", "am",
              "also", "much", "though", "would"]
